apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: order-service
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: order-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: order-service
    spec:
      containers:
      - env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql/eventuate
        - name: SPRING_DATASOURCE_USERNAME
          value: mysqluser
        - name: SPRING_DATASOURCE_PASSWORD
          value: mysqlpw
        - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          value: com.mysql.jdbc.Driver
        - name: EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS
          value: kafka:9092
        - name: EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING
          value: zookeeper:2181
        - name: ENDPOINTS_SENSITIVE
          value: "false"
        image: order-service:0.0.1-SNAPSHOT
        imagePullPolicy: Never
        name: ms-order-service
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}