apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: order-service
  name: order-service
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    nodePort: 32306
    targetPort: 8080
  selector:
    io.kompose.service: order-service
status:
  loadBalancer: {}
